INSERT INTO jobs (id, title, slug, location, department, description, responsibilities, skills, benefits, created_at, updated_at)
VALUES
(gen_random_uuid(), 'Concrete Inspector - Entry Level', 'concrete-inspector-entry-level-canton', 'Canton, MI', 'Geoenvironmental', 'The Mannik & Smith Group, Inc. (MSG) is seeking a motivated entry-level Concrete Inspector to join our Geoenvironmental team. This position offers hands-on experience in concrete testing and inspection procedures.', '["Perform concrete slump tests and air content measurements", "Document concrete placement and curing conditions", "Conduct visual inspections for defects and non-conformances", "Maintain detailed field notes and test records", "Follow ASTM standards for concrete testing procedures"]'::jsonb, '["Attention to detail", "Physical stamina", "Basic construction knowledge", "Ability to work in outdoor conditions", "Strong communication skills"]'::jsonb, '["Competitive salary", "Health insurance", "Training and certification support", "Career development opportunities"]'::jsonb, NOW(), NOW()),

(gen_random_uuid(), 'Concrete Testing Technician', 'concrete-testing-technician-downtown-chicago', 'Downtown Chicago, IL', 'Geoenvironmental', 'MSG is looking for a Concrete Testing Technician to perform quality assurance testing on concrete samples. This role is critical for ensuring structural integrity and compliance with project specifications.', '["Operate concrete testing equipment including compressive strength machines", "Prepare and cure concrete cylinders and samples", "Perform break tests on hardened concrete", "Record and analyze test data", "Assist in preparation of test reports"]'::jsonb, '["Concrete testing procedures", "Equipment operation and maintenance", "Data analysis", "Quality assurance protocols", "ASTM standard knowledge"]'::jsonb, '["Medical, dental, and vision coverage", "401(k) matching", "Continuing education assistance", "Safety equipment provided"]'::jsonb, NOW(), NOW()),

(gen_random_uuid(), 'Junior Concrete Inspector', 'junior-concrete-inspector-naperville', 'Naperville, IL', 'Geoenvironmental', 'Join MSG''s Geoenvironmental department as a Junior Concrete Inspector. Gain valuable experience inspecting concrete construction, testing materials, and ensuring project compliance with engineering specifications.', '["Inspect concrete placement and consolidation", "Monitor concrete curing schedules", "Perform in-place strength testing", "Collect concrete samples for laboratory analysis", "Maintain inspection logs and photographic records"]'::jsonb, '["Concrete technology understanding", "Field inspection experience", "Laboratory procedures", "Report writing", "Construction terminology"]'::jsonb, '["Health and wellness programs", "Annual training budget", "Paid time off", "Professional development support"]'::jsonb, NOW(), NOW()),

(gen_random_uuid(), 'Concrete Quality Assurance Specialist', 'concrete-qa-specialist-aurora', 'Aurora, IL', 'Geoenvironmental', 'MSG seeks an experienced Concrete Quality Assurance Specialist to oversee concrete testing and inspection operations. This position requires strong technical knowledge and quality management experience in concrete construction.', '["Develop and implement concrete testing protocols", "Supervise concrete testing activities", "Review test results and specifications", "Coordinate with project managers and contractors", "Maintain quality assurance documentation"]'::jsonb, '["Concrete quality standards", "ACI guidelines knowledge", "Supervision experience", "Quality control procedures", "Report documentation"]'::jsonb, '["Comprehensive benefits package", "Flexible scheduling", "Career advancement opportunities", "Technical certification support"]'::jsonb, NOW(), NOW()),

(gen_random_uuid(), 'Senior Concrete Inspector', 'senior-concrete-inspector-joliet', 'Joliet, IL', 'Geoenvironmental', 'MSG''s Geoenvironmental division is hiring a Senior Concrete Inspector with extensive field experience. This leadership role involves overseeing concrete testing operations and mentoring junior staff on large-scale projects.', '["Lead concrete inspection teams on major projects", "Perform advanced concrete testing procedures", "Train and mentor junior inspectors", "Ensure compliance with contract specifications", "Prepare technical reports and recommendations"]'::jsonb, '["15+ years concrete inspection experience", "Team leadership", "Advanced testing methods", "Project management", "Client communication"]'::jsonb, '["Executive benefits", "Performance bonuses", "Mentorship opportunities", "Continuing education funding"]'::jsonb, NOW(), NOW()),

(gen_random_uuid(), 'Concrete Inspection Field Technician', 'concrete-inspection-field-tech-elgin', 'Elgin, IL', 'Geoenvironmental', 'MSG is recruiting a Concrete Inspection Field Technician for ongoing concrete quality monitoring on active construction sites. This hands-on role requires technical knowledge of concrete behavior and testing procedures.', '["Conduct slump, temperature, and air content tests", "Monitor concrete strength development", "Perform compression testing on samples", "Document construction sequences and conditions", "Coordinate with construction crews"]'::jsonb, '["Concrete testing expertise", "Equipment proficiency", "Field site experience", "Safety protocols", "Technical documentation"]'::jsonb, '["Competitive compensation", "Health benefits", "On-the-job training", "Equipment provided"]'::jsonb, NOW(), NOW()),

(gen_random_uuid(), 'Concrete Materials Inspector', 'concrete-materials-inspector-waukegan', 'Waukegan, IL', 'Geoenvironmental', 'MSG''s Geoenvironmental team needs a Concrete Materials Inspector to verify incoming concrete materials and monitor quality throughout projects. This position ensures all concrete meets engineering and quality requirements.', '["Inspect concrete delivery and placement", "Verify material certifications and documentation", "Perform field concrete testing", "Assess concrete workability and consistency", "Maintain material traceability records"]'::jsonb, '["Concrete material properties", "Testing procedures", "Quality verification", "Documentation skills", "ACI standards knowledge"]'::jsonb, '["Medical and dental benefits", "Safety training provided", "Career growth potential", "Flexible hours"]'::jsonb, NOW(), NOW()),

(gen_random_uuid(), 'Concrete Strength Testing Technician', 'concrete-strength-testing-technician-cicero', 'Cicero, IL', 'Geoenvironmental', 'MSG is looking for a Concrete Strength Testing Technician to perform compressive strength tests and evaluate concrete quality. This position plays a vital role in ensuring structural safety and project compliance.', '["Operate compressive strength testing equipment", "Prepare concrete test specimens", "Record and analyze strength data", "Interpret test results against specifications", "Generate testing reports"]'::jsonb, '["Concrete strength testing", "Laboratory operations", "Equipment calibration", "Data interpretation", "Statistical analysis"]'::jsonb, '["Professional development opportunities", "Health insurance", "Retirement benefits", "Certification support"]'::jsonb, NOW(), NOW()),

(gen_random_uuid(), 'Experienced Concrete Inspector', 'experienced-concrete-inspector-arlington', 'Arlington Heights, IL', 'Geoenvironmental', 'MSG seeks an experienced Concrete Inspector with a proven track record in large commercial and civil construction projects. This role involves complex concrete testing and quality oversight on high-profile developments.', '["Manage concrete testing programs", "Oversee multiple project inspections", "Interpret engineering drawings and specifications", "Conduct advanced testing procedures", "Advise on concrete-related issues"]'::jsonb, '["10+ years inspection experience", "Commercial project knowledge", "Advanced technical skills", "Project coordination", "Problem-solving abilities"]'::jsonb, '["Excellent compensation package", "Comprehensive benefits", "Project bonuses", "Advanced training opportunities"]'::jsonb, NOW(), NOW()),

(gen_random_uuid(), 'Concrete Testing Associate', 'concrete-testing-associate-evanston', 'Evanston, IL', 'Geoenvironmental', 'Join MSG''s Geoenvironmental team as a Concrete Testing Associate. This position offers a great opportunity to develop expertise in concrete testing, material science, and quality assurance procedures.', '["Assist in concrete testing operations", "Prepare test samples and equipment", "Record test data and observations", "Support senior technicians on projects", "Learn concrete inspection best practices"]'::jsonb, '["Willingness to learn", "Technical aptitude", "Attention to detail", "Communication skills", "Physical capability"]'::jsonb, '["Entry-level competitive pay", "Health benefits", "Comprehensive training program", "Mentorship and career guidance"]'::jsonb, NOW(), NOW());
