-- UPDATE JUNIOR CONCRETE INSPECTOR JOBS WITH DETAILED DESCRIPTIONS

-- Denver - Focus on field testing and documentation
UPDATE jobs SET description = 'As a Junior Concrete Inspector, you will be responsible for conducting pre-placement inspections to verify formwork, reinforcing steel, and base preparation meet specifications. Perform slump tests, air content measurements, and temperature monitoring during concrete placement. Document all field observations and test results in detailed daily reports. Inspect concrete consolidation, finishing, and initial curing procedures for compliance. Coordinate with project managers and contractors regarding concrete placement schedules. Verify reinforcing steel placement, spacing, and cover per project drawings. Monitor concrete curing and protection methods throughout the specified curing period. Prepare written field reports summarizing daily concrete work and any non-conformances observed. Work in various weather conditions and maintain accurate records on job sites.

Requirements: High School Diploma or equivalent GED, 1-3 years experience in concrete inspection or construction quality control, valid driver''s license and reliable transportation, strong written and verbal communication abilities, ability to read and interpret construction documents and specifications.

Preferred Certifications: ACI Concrete Construction Special Inspector Certification, ICC Reinforced Concrete Special Inspector, or PCI Quality Control Technician Certification (at least one required).' WHERE slug = 'junior-concrete-inspector-denver';

-- Austin - Focus on specifications compliance and visual inspections
UPDATE jobs SET description = 'In this position as Junior Concrete Inspector, you will verify compliance with all project specifications and technical requirements. Perform visual inspections of concrete surfaces for defects, discoloration, and surface finish quality. Monitor placement procedures to ensure proper sequencing and consolidation techniques are followed. Prepare and maintain detailed field notes and documentation throughout each workday. Interact professionally with client representatives, engineers, and construction crews at project sites. Conduct reinforcement steel inspections prior to concrete placement, verifying proper layout and cover distances. Observe concrete finishing operations including screeding, floating, and troweling activities. Document cure time verification and protection measures implemented on placed concrete. Submit comprehensive field reports with photographic evidence of non-conforming work. Adapt to outdoor work environments in changing weather and site conditions.

Requirements: High school diploma or GED certification, 1-3 years relevant experience in concrete or construction inspection, current driver''s license, excellent communication and documentation skills, proficiency in reading blueprints and construction specifications.

Required Certifications (minimum one): ACI Special Inspector Certification, ICC Reinforced Concrete Inspector, or equivalent concrete inspection certification.' WHERE slug = 'junior-concrete-inspector-austin';

-- Portland - Focus on material testing and safety procedures
UPDATE jobs SET description = 'As Junior Concrete Inspector, you will oversee material testing and safety compliance at concrete placement sites. Perform concrete testing including slump, temperature, air content, and cylinder preparation for compressive strength testing. Verify all materials meet specification requirements before placement authorization. Inspect safety equipment, signage, and work procedures for OSHA compliance. Monitor concrete curing conditions and document moisture levels and temperature control measures. Prepare detailed field inspection reports with all testing data and observations recorded. Work collaboratively with quality assurance teams and project management personnel. Inspect formwork removal procedures and concrete surface conditions post-removal. Verify proper spacing and protection of reinforcing steel installations. Submit daily reports documenting all testing, inspections, and observations made on site.

Requirements: High school diploma or GED, 1-3 years concrete or construction quality assurance experience, valid driver''s license, strong technical writing and communication skills, ability to work independently and follow detailed specifications.

Required Certifications (at least one): ACI Concrete Construction Special Inspector, ICC Special Inspector certification, or PCI Quality Control Technician.' WHERE slug = 'junior-concrete-inspector-portland';

-- Miami - Focus on placement monitoring and coordination
UPDATE jobs SET description = 'In this Junior Concrete Inspector role, you will monitor all phases of concrete placement operations from arrival through final curing. Coordinate with delivery trucks, pumping operations, and placement crews to ensure smooth workflow and specification compliance. Conduct real-time inspections during concrete consolidation and finishing to verify quality standards are met. Prepare inspection checklists and verify readiness before concrete placement authorization. Document placement procedures with written notes and photographic evidence throughout the day. Maintain communication with project engineers and contractors regarding any non-conforming work or schedule adjustments. Inspect concrete surfaces daily for proper curing conditions and protection measures. Submit detailed field reports summarizing placement activities, testing results, and any corrective actions required. Work outdoors in tropical weather conditions and maintain professional site presence.

Requirements: High school diploma or equivalent, 1-3 years experience in concrete inspection or construction quality control, valid driver''s license, excellent verbal and written communication skills, ability to interact professionally with multiple stakeholders.

Preferred Certifications (one required): ACI Concrete Construction Special Inspector, ICC Reinforced Concrete Inspector, or PCI Quality Control Level II.' WHERE slug = 'junior-concrete-inspector-miami';

-- Nashville - Focus on curing and protection procedures
UPDATE jobs SET description = 'As Junior Concrete Inspector, you will ensure proper curing and protection of placed concrete throughout the project. Verify curing methods comply with specifications including wet curing, curing compounds, and temperature control measures. Inspect protection systems preventing weather damage, traffic damage, and premature loading. Monitor concrete strength development and document when removal of formwork and shoring is permitted. Prepare detailed inspection reports documenting all curing and protection observations made daily. Conduct post-placement inspections to verify concrete quality and identify any defects requiring remediation. Work with project teams to develop and implement curing schedules and protection plans. Inspect reinforcing steel and embedded items verification before concrete hardening. Perform surface condition inspections and document any spalling, cracking, or other defects. Submit comprehensive reports with recommendations for corrective actions.

Requirements: High school diploma or GED certification, 1-3 years concrete inspection or construction experience, valid driver''s license, strong technical communication skills, ability to read architectural and engineering drawings.

Required Certifications (minimum one): ACI Special Inspector for Concrete Construction, ICC Reinforced Concrete Inspector, or equivalent certification.' WHERE slug = 'junior-concrete-inspector-nashville';

-- UPDATE SENIOR CONCRETE INSPECTOR JOBS WITH DETAILED DESCRIPTIONS

-- San Francisco - Focus on team leadership and oversight
UPDATE jobs SET description = 'As Senior Concrete Inspector, you will lead and oversee all concrete inspection activities for major construction projects. Manage a team of junior inspectors and coordinate their assignments to ensure comprehensive project coverage. Develop inspection plans and quality control procedures aligned with project specifications and industry standards. Conduct advanced concrete testing and verify laboratory results meet design requirements. Review and approve all field reports and documentation prepared by junior staff. Coordinate directly with project engineers, architects, and client representatives on quality matters. Implement corrective actions for non-conforming work and verify effectiveness of remediation. Mentor junior inspectors in proper inspection techniques, testing procedures, and professional standards. Prepare comprehensive quality reports for client distribution and project records. Manage inspection schedules and coordinate with construction schedule to prevent work delays.

Requirements: PE License or equivalent professional credential, 6-7 years concrete inspection experience with demonstrated leadership, valid driver''s license, excellent project management and communication skills, proficiency with construction software and digital reporting systems.

Required Certifications: ACI Concrete Construction Special Inspector, ICC Reinforced Concrete Special Inspector, and PCI Quality Control Technician Level II (or equivalent advanced certifications).' WHERE slug = 'senior-concrete-inspector-san-francisco';

-- New York - Focus on complex project management
UPDATE jobs SET description = 'In this Senior Concrete Inspector position, you will manage concrete quality inspection for large, complex building and infrastructure projects. Develop comprehensive inspection strategies tailored to project scope, schedule, and specifications. Lead inspection teams and ensure consistent application of quality standards throughout placement and curing phases. Conduct advanced inspections of specialized concrete elements and high-performance concrete systems. Provide technical guidance on problem-solving and specification interpretation to project teams. Prepare detailed inspection protocols and quality assurance documentation for project records. Interface with building officials, engineers, and owner representatives on concrete quality issues. Implement quality assurance procedures and conduct audits of inspection personnel and processes. Oversee concrete testing programs and verify laboratory compliance with standards. Develop progress reports documenting inspection activities, findings, and any required corrective actions.

Requirements: PE License or equivalent professional engineering credential, 6-7 years senior-level concrete inspection experience on complex projects, valid driver''s license, strong project management and communication abilities, experience with advanced construction technologies and digital platforms.

Required Certifications: ACI Concrete Construction Special Inspector, ICC Reinforced Concrete Special Inspector, ACI Concrete Quality Technician certification.' WHERE slug = 'senior-concrete-inspector-new-york';

-- Boston - Focus on code compliance and regulations
UPDATE jobs SET description = 'As Senior Concrete Inspector, you will ensure all concrete work meets building codes, regulations, and project specifications. Interpret complex technical specifications and building code requirements for project teams. Conduct comprehensive inspections of formwork, reinforcement, materials, and concrete placement procedures. Verify compliance with ACI standards, local building codes, and international concrete standards. Review and interpret structural drawings and specifications to establish inspection requirements. Document all inspections with detailed reports and photographic evidence of compliance or non-conformance. Coordinate with code officials and building departments on compliance matters and required corrective actions. Manage concrete testing programs and verify results meet design specifications. Provide technical consultation on concrete-related issues to project management and engineering teams. Lead training sessions for project personnel on concrete inspection and quality procedures.

Requirements: Professional Engineer License, 6-7 years experience in concrete inspection with code compliance focus, valid driver''s license, in-depth knowledge of building codes and concrete standards, excellent technical writing and documentation skills.

Required Certifications: ACI Concrete Construction Special Inspector, ICC Building Inspector, ACI Concrete Strength Testing Technician certification.' WHERE slug = 'senior-concrete-inspector-boston';

-- Atlanta - Focus on technical expertise and mentorship
UPDATE jobs SET description = 'In this Senior Concrete Inspector role, you will provide technical expertise and mentorship on all concrete-related quality matters. Train and mentor junior inspection staff in advanced inspection techniques and professional standards. Conduct specialized inspections of unique concrete systems and high-performance concrete applications. Review all inspection reports and documentation prepared by team members for accuracy and completeness. Serve as technical expert on concrete issues, providing guidance to project engineers and management. Implement quality assurance procedures and conduct periodic audits of inspection processes and personnel. Develop inspection procedures specific to project requirements and concrete specifications. Coordinate concrete testing programs and interpret results for compliance determination. Prepare comprehensive quality reports and present findings to project stakeholders. Lead problem-solving efforts for concrete quality issues and non-conformances.

Requirements: PE License or equivalent professional credential, 6-7 years concrete inspection experience with demonstrated technical expertise, valid driver''s license, strong interpersonal and training skills, experience managing inspection teams.

Required Certifications: ACI Concrete Construction Special Inspector, ICC Reinforced Concrete Inspector, PCI Quality Control Technician, and ACI Concrete Strength Testing Technician.' WHERE slug = 'senior-concrete-inspector-atlanta';

-- Seattle - Focus on advanced inspection and detailed reporting
UPDATE jobs SET description = 'As Senior Concrete Inspector, you will conduct advanced concrete inspections and prepare comprehensive documentation for all placement activities. Perform specialized inspections of complex concrete elements and demanding applications. Utilize advanced testing equipment and verification methods to assess concrete quality and compliance. Develop detailed inspection checklists and quality plans tailored to project-specific requirements. Coordinate concrete testing programs and verify laboratory quality and equipment calibration. Prepare detailed inspection reports with technical analysis and recommendations for corrective actions. Conduct inspections of formwork systems, reinforcement placement, and concrete protection measures. Mentor junior inspectors and provide technical guidance on difficult inspection situations. Manage inspection schedules and coordinate with construction activities to optimize efficiency. Interface with engineers, architects, and client representatives on technical concrete matters and quality issues.

Requirements: Professional Engineer License, 6-7 years senior-level concrete inspection experience, valid driver''s license, expertise in concrete materials and construction methods, proficiency with inspection documentation systems.

Required Certifications: ACI Concrete Construction Special Inspector, ICC Reinforced Concrete Special Inspector, PCI Quality Control Technician Level II certification.' WHERE slug = 'senior-concrete-inspector-seattle';
